### PR TITLE
This will make it possible to use docker secrets with stackstorm image.

### PR DESCRIPTION
**Pull request by Smeds**
New version of previous remove pull-request

This pull request will make it possible to use [docker secrets](https://docs.docker.com/engine/swarm/secrets) to mask user credentials when a container is created. To use the feature, just append "_FILE" to the regular environment variables and assign it the path where the secret is stored. It's a nice feature to have when using [ansible-containers](https://github.com/ansible/ansible-container), since you then can use [ansible vault](http://docs.ansible.com/ansible/latest/playbooks_vault.html) to store credentials.

Follow the steps below to build stackstorm with docker secrets. I haven't changed the mongo credentials since I wasn't able to successfully change them using current docker compose file.

# Howto use docker secrets

## Step4: Build docker image
You need to build the image using the dockerfile found in this commit.
> cd images/stackstorm
> docker build . --tag stackstorm/stackstorm:latest

### CODE REVIEW

**Comment by emptywee** [comment]
That (seems like) will break https://github.com/StackStorm/st2-docker/tree/master/runtime/kubernetes-1ppc stuff which is based heavily on env variables to setup components in the containers and will require most of the configuration part to be re-written.

**Comment by Smeds** [comment]
I will see if I can get access to a kubernetes environment to make the necessary updates for it to not break stuff

**Comment by dzimine** [comment]
Hi @Smeds 
do you foresee any cycles on completing this? 
Thanks much!

**Comment by Smeds** [comment]
Hi @dzimine 

At the moment I haven't access to a kubernetes environment, which makes a bit hard for me to develop and test a solution right now. But we are planing of setting up one in the future, maybe within 6-12 month.

**Pull request closed without merging**
