### PR TITLE
Tag image with the version of StackStorm

### PR DESCRIPTION
**Pull request by warrenvw**
With this PR, we change the file hierarchy as follows:

```
images/stackstorm/Dockerfile -> images/stackstorm/${VERSION}/Dockerfile
```

where `${VERSION}` is the version of StackStorm (e.g. `2.2.1`, `2.3.0`, ...).

This allows us to create images tagged with the version of StackStorm. We will only support the image for the latest version of StackStorm. Other versions will be on a best effort basis.

We will delete the oldest version such that there will be no more than FOUR versioned directories at any given time.

### CODE REVIEW

**Comment by shusugmt** [comment]
Not directly relevant to this PR but we need a solid policy how we choose pkg version (number part after hyphen / pre-release version in [semver](http://semver.org/#spec-item-9)) for each component:

```
ARG ST2_VERSION="2.3.0-2"
ARG ST2WEB_VERSION="2.3.0-1"
ARG ST2MISTRAL_VERSION="2.3.0-6"
```

Possible solutions are 1. check the release everyday and change it all manually, or 2. omit that part and let package manager decide, or what else?

**Comment by warrenvw** [comment]
I agree we need a solid policy for how we choose pkg version.

For the stable released packages that these images pertain to by default, I think the version (including the pkg version) is really only changed at release. I haven't observed them change otherwise.

Having said that, generally, the latest pkg version is the one we'd want.. so maybe the default should be the latest and as already coded, the defaults can be overridden if they're not correct.

Here's one way to determine the latest pkg version for version 2.2.1 of `st2`:

```
$ apt-cache madison st2 | cut -f 2 -d '|' | tr -d '[ \t]' | grep 2.2.1 | head -1
2.2.1-6
```

How this may get hooked into the machinery is TBD.

**Comment by shusugmt** [comment]
LGTM!

**Comment by warrenvw** [comment]
```
$ apt-cache madison st2 | cut -f 2 -d '|' | tr -d '[ \t]' | grep 2.2.1 | head -1
2.2.1-6
```

Apparently `apt-cache madison st2` returns a version that `apt-get install` cannot find.

**Comment by warrenvw** [comment]
Problem was that I'd configured apt-cache to look at `staging-stable` instead of just `stable`. So all is well now.

**Pull request merged**
