### PR TITLE
Add st2.d processing

### PR DESCRIPTION
**Pull request by warrenvw**
After st2api starts, `st2.sh` runs the `*.sh` scripts in `/st2-docker/st2.d`. The environment variables defined in `stackstorm.env` are available to the scripts.

NOTE: To run scripts on boot before any st2 services start, place `*.sh` scripts in the `/st2-docker/entrypoint.d` directory.

### CODE REVIEW

**Comment by shusugmt** [comment]
Great patch. I see still WIP labeled but would like to leave some comments:

- We should mention in *root* README.md that `/st2-docker/st2.d` will do nothing if we are running on 1ppc mode (it's obvious by nature, but still better to put it)
- Also we should mention the difference between `/st2-docker/entrypoint.d` and `/st2-docker/st2.d` in *root* README.md, not only in `runtime/st2.d/README.md`
- Can you remove the `VOLUME` instruction too, within this PR?

**Comment by warrenvw** [comment]
We've moved `/entrypoint.d` to `/st2-docker/entrypoint.d`. There's no great mechanism to tell people that this directory has moved. That is, there's no change log, or versioning for changes to st2-docker. The versions we're using are based on version of StackStorm itself.

**Comment by shusugmt** [comment]
> That is, there's no change log, or versioning for changes to st2-docker that would indicate potentially backward incompatible changes.

True. And handling this with having separate version scheme will complicate things, so I prefer providing CHANGELOG, which is bare minimum.

**Comment by armab** [comment]
+1 great idea to start maintaining CHANGELOG file

**Comment by DoriftoShoes** [comment]
w00t.  Looks good man.

**Pull request merged**
