### PR TITLE
Change to use Ubuntu key server at port 80

### PR DESCRIPTION
**Pull request by lshahar**

### CODE REVIEW

**Comment by shusugmt** [comment]
Duplicate of #35 

@lshahar Thanks for the PR. Can you please open a separate PR for changing key server port (and hopefully with the reason why we need it)

**Comment by lshahar** [comment]
I have remove chatops installation,
Regrading to reason changing the port , the default keyserver port is 11371 , that not standard port and at some places block it, so I have change it to common port (80)

**Comment by shusugmt** [comment]
@lshahar Thanks. One more thing, please squash into a single commit.

**Comment by warrenvw** [comment]
Closing this PR since chatops is already available in `master`. Separately, I'll review the change to use `hkp://keyserver.ubuntu.com:80` and submit a new PR.

I am not sure why we need the docker client inside the `stackstorm` image. If this is important, please submit another issue. In any case, it has nothing to do with the subject of this PR.

**Pull request closed without merging**
