### PR TITLE
Add BATS testing

### LINKED ISSUE #197: Add Integration Tests
There is a CI check which mimicks quick smoke tests for the Docker deployment to verify it somewhat works:
https://github.com/StackStorm/st2-docker/blob/02c7d2f0a046dbc3cb2b6aac788ce065c1fd6bde/.circleci/config.yml#L33-L38

Better way would be following the solution in existing stackstorm-ha repo and adopt proper `BATS` integration tests:
https://github.com/StackStorm/stackstorm-ha/blob/master/tests/st2tests.sh that would check system aliveness.

Implement these tests so the proper `docker-compose` entry point to run would be as simple as: 
`docker-compose run tests`

### PR DESCRIPTION
**Pull request by minsis**
Adds a basic BATS smoke test to verify the st2-docker stack is functional.

Closes #197

### CODE REVIEW

**Comment by minsis** [comment]
https://github.com/StackStorm/st2-docker/blob/a6aa05c890005eb2ddc87253c2ac42a62a078469/.circleci/config.yml#L29-L39

I guess I should've read this a bit closer for the circleci stuff. I'm assuming the above only needs to be replaced with something as simple as 

```yaml
command: docker-compose -f tests/st2tests.yaml
```

The only thing I'm not sure about is this container does an exit code. I'm not sure how circleci handles that? I'm guessing it passes on `== 0` and fails on `!= 0`

**Comment by armab** [comment]
That's correct. Non-zero exit code should indicate a failure in CircleCI.

**Comment by minsis** [comment]
Looks like we're in a bit of a dilemma here. Docker-compose by default uses the top-level directory name for creating its namespace. In the circle ci config its set to ~/docker.

So a couple of things:
1. We can rename `~/docker` to `~/st2-docker`
2. I can try and play around with the [$CIRCLE_WORKING_DIRECTORY environment variable](https://circleci.com/docs/2.0/configuration-reference/#lessjobnamegreater) . It would be adding it the network naming scheme inside the compose file and I dont know if that can be done.

Step 1 is easiest way to deal with this unless there was some specific reason the working directory needed to be called `docker`

**Comment by minsis** [comment]
Step 2 above fails.

```yaml
networks:
   ${CIRCLE_WORKING_DIRECTORY:-st2-docker_private}:
    external: true
```

```shell
WARNING: Some networks were defined but are not used by any service: ${CIRCLE_WORKING_DIRECTORY:-st2-docker_private}
ERROR: Service "st2test" uses an undefined network "st2-docker_private"
```

**Comment by minsis** [comment]
I changed the working dir name to `~/st2-docker` and build is passing now.

closes #197

**Review by armab — APPROVED** [review]
Great work :100: 

Thanks a lot!

**Pull request merged**
